# Generated by Django 5.0.4 on 2024-10-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
